#!/usr/bin/bash

USER=vivlim
FSCRYPTED_HOMEDIR=/home/$USER
SCRIPTDIR=$(dirname $(realpath -- "$0";))
PASSPHRASE_GETTER=$SCRIPTDIR/fscrypt-user-get-passphrase

if [ ! -e $PASSPHRASE_GETTER ]; then
  echo "Passphrase getter script doesn't exist at $PASSPHRASE_GETTER. Please create it or copy fscrypt-user-get-passphrase.sample-interactive to that location"
  sleep 5
  exit 1
fi

# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
else
  echo "couldn't source nix profile?"
  sleep 5
  exit 1
fi
# End Nix

#check if user is decrypted
sudo fscrypt status $FSCRYPTED_HOMEDIR | awk '{if ($1 ~ /^Unlocked/) { if ($2 =="Yes") exit 0; else exit 1}}'
if [ $? -eq 0 ]
then
  echo "$FSCRYPTED_HOMEDIR is already unlocked."
  xauth list | grep unix`echo $DISPLAY | cut -c10-12` > /tmp/xauth
  sudo su $USER -l -c "xauth add `cat /tmp/xauth`; export DISPLAY=$DISPLAY;$@"
  sleep 5
  exit 0

else
  echo "$FSCRYPTED_HOMEDIR is locked."
  echo "calling $PASSPHRASE_GETTER to get passphrase"
  passphrase="$($PASSPHRASE_GETTER)"
  if [ $? -ne 0 ]
  then
    echo "Passphrase not entered. Exiting.";
    sleep 5
    exit 1
  fi

sudo fscrypt unlock --quiet "$FSCRYPTED_HOMEDIR" <<< "$passphrase"
if [ $? -eq 0 ]
  then
    echo "Successfully unlocked $FSCRYPTED_HOMEDIR."
  else
    echo "Failed to unlock $FSCRYPTED_HOMEDIR. Aborting."
    exit 1
  fi
fi

xauth list | grep unix`echo $DISPLAY | cut -c10-12` > /tmp/xauth
(sudo su $USER -l -c "xauth add `cat /tmp/xauth`; DISPLAY=$DISPLAY $@") &

nix-shell -p yad --run "$SCRIPTDIR/tray-icon $USER"

STOP_PROCESSES_ATTEMPT=1
while [ "$(ps --no-headers -u $USER | wc -l)" -gt 0 ] && [ $STOP_PROCESSES_ATTEMPT -lt 10 ]
do
  if [ $STOP_PROCESSES_ATTEMPT -lt 6 ]; then
    echo "Trying to stop user processes using SIGTERM (attempt $STOP_PROCESSES_ATTEMPT)"
    sudo pkill -u $USER
  else
    echo "Trying to stop user processes using SIGKILL (attempt $STOP_PROCESSES_ATTEMPT)"
    sudo pkill -9 -u $USER
  fi

  if [ "$(ps --no-headers -u $USER | wc -l)" -gt 0 ]; then
    echo "Some processes remain:"
    ps -u $USER 
    echo
  fi
  ((STOP_PROCESSES_ATTEMPT++))
  sleep 1
done

echo "Locking $FSCRYPTED_HOMEDIR."

sudo fscrypt lock $FSCRYPTED_HOMEDIR
if [ $? -ne 0 ]
then
  echo "$FSCRYPTED_HOMEDIR didn't lock cleanly, attempting to kill leftover processes that are still using encrypted files."
  sudo sh -c 'find "$FSCRYPTED_HOMEDIR" -print0 | xargs -0 fuser -k'
  echo "Attempt lock again."
  sudo fscrypt lock $FSCRYPTED_HOMEDIR
fi

