#!/usr/bin/bash

USER=vivlim
FSCRYPTED_HOMEDIR=/home/$USER
SCRIPTDIR=$(dirname $(realpath -- "$0";))
PASSPHRASE_GETTER=$SCRIPTDIR/fscrypt-user-get-passphrase

echo "$USE_ZENITY_LOGGING"
if ! [ -z "$USE_ZENITY_LOGGING" ]; then
  echo "using zenity logs"
  logging_type="zenity"
else
  echo "using stdout logs"
  logging_type="stdout"
fi

source "$SCRIPTDIR/utils.sh" steamdeck-nix-multiuser "steamdeck fscrypt user profile" "$logging_type"
log_init
log_init_progress

log_progress_message "Initializing"
if [ ! -e $PASSPHRASE_GETTER ]; then
  log_message "Passphrase getter script doesn't exist at $PASSPHRASE_GETTER. Please create it or copy fscrypt-user-get-passphrase.sample-interactive to that location"
  log_end_show_all
  exit 1
fi

# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
else
  log_message "couldn't source nix profile?"
  log_end_show_all
  exit 1
fi
# End Nix

log_progress
#check if user is decrypted
sudo fscrypt status $FSCRYPTED_HOMEDIR | awk '{if ($1 ~ /^Unlocked/) { if ($2 =="Yes") exit 0; else exit 1}}'
if [ $? -eq 0 ]
then
  log_message "$FSCRYPTED_HOMEDIR is already unlocked."
  xauth list | grep unix`echo $DISPLAY | cut -c10-12` > /tmp/xauth
  log_end
  sudo su $USER -l -c "xauth add `cat /tmp/xauth`; export DISPLAY=$DISPLAY;$@"
  exit 0

else
  log_progress_message "$FSCRYPTED_HOMEDIR is locked. calling $PASSPHRASE_GETTER to get passphrase."
  passphrase="$($PASSPHRASE_GETTER)"
  if [ $? -ne 0 ]
  then
    log_message "Passphrase not entered. Exiting.";
    sleep 4
    log_end
    exit 1
  fi

sudo fscrypt unlock --quiet "$FSCRYPTED_HOMEDIR" <<< "$passphrase"
if [ $? -eq 0 ]
  then
    log_progress_message "Successfully unlocked $FSCRYPTED_HOMEDIR."
  else
    log_message "Failed to unlock $FSCRYPTED_HOMEDIR. Aborting."
    sleep 4
    log_end
    exit 1
  fi
fi

xauth list | grep unix`echo $DISPLAY | cut -c10-12` > /tmp/xauth
log_end
(sudo su $USER -l -c "xauth add `cat /tmp/xauth`; DISPLAY=$DISPLAY $@") &

nix-shell -p yad --run "$SCRIPTDIR/tray-icon $USER"

STOP_PROCESSES_ATTEMPT=1
while [ "$(ps --no-headers -u $USER | wc -l)" -gt 0 ] && [ $STOP_PROCESSES_ATTEMPT -lt 10 ]
do
  if [ $STOP_PROCESSES_ATTEMPT -lt 6 ]; then
    echo "Trying to stop user processes using SIGTERM (attempt $STOP_PROCESSES_ATTEMPT)"
    sudo pkill -u $USER
  else
    echo "Trying to stop user processes using SIGKILL (attempt $STOP_PROCESSES_ATTEMPT)"
    sudo pkill -9 -u $USER
  fi

  if [ "$(ps --no-headers -u $USER | wc -l)" -gt 0 ]; then
    echo "Some processes remain:"
    ps -u $USER 
    echo
  fi
  ((STOP_PROCESSES_ATTEMPT++))
  sleep 1
done

echo "Locking $FSCRYPTED_HOMEDIR."

sudo fscrypt lock $FSCRYPTED_HOMEDIR
if [ $? -ne 0 ]
then
  echo "$FSCRYPTED_HOMEDIR didn't lock cleanly, attempting to kill leftover processes that are still using encrypted files."
  sudo sh -c 'find "$FSCRYPTED_HOMEDIR" -print0 | xargs -0 fuser -k'
  echo "Attempt lock again."
  sudo fscrypt lock $FSCRYPTED_HOMEDIR
fi

