#!/usr/bin/bash
SCRIPTDIR=$(dirname $(realpath -- "$0";))
source "$SCRIPTDIR/utils.sh"

ARCHHOMEDIR="/home/deck/archxfcehome"

# terrifying workaround: xfce refuses to start (just shows a white screen forever) if the use_compositing property is in xfwm4.xml.
# remove the line from that file and don't worry too much about it
xfwm4xmlpath="$ARCHHOMEDIR/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"

if [ -f "$xfwm4xmlpath" ]; then
    sed -i '/<property name="use_compositing" type="bool" value="true"\/>/d' "$xfwm4xmlpath"
fi

"$SCRIPTDIR/x11docker" \
-d $SCRIPTDIR/../x11docker-dockerfiles/xfce-arch `# read dockerfile from stdin (it's written lower in this script)` \
-- `# pass following args to x11docker` \
--desktop `# we want to run a desktop environment inside of a window` \
--network `# allow container to access the network` \
--sudouser `# allow user to become root using su, default password is x11docker` \
--gpu \
--webcam `# allow container to access the webcam` \
--pulseaudio=host `# allow container to play audio` \
--dbus `# support dbus` \
--home="$ARCHHOMEDIR" `# create a persistent home directory across container runs` \
--cap-default \
--init=systemd `# this might not be necessary but maybe it'll reduce the chances of random things breaking. todo: see if it can be removed safely` \
--backend=podman \
$@
